### ISSUE TITLE
How to make only part of rows expandable.

### ISSUE THREAD

**Issue by niba** [react-component/table#188] opened 2018-02-19 10:37 UTC
In my application, I want to draw an expandable icon for these rows that have children. With the current API, this scenario is not possible. 
There should be a function similar to this:
`isRowExpandable = (record) => boolean` which default is () => true. Thanks to that user would be able to decide which rows he wants to make expandable.

**Comment by yesmeck** [comment] 2018-02-19 17:37
Duplicate of https://github.com/ant-design/ant-design/issues/7817

**Closed by yesmeck** 2018-02-19 17:37 UTC
